services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
