services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python render_start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 10000
